name: Bug report
description: "Use this template if you're running into bugs or other issues"
labels:
  - bug
body:
  - type: input
    id: minecraft-version
    attributes:
      label: Minecraft version
      description: >-
        The version of Minecraft you are using this datapack with.
      placeholder: "Example: 1.19.4"
    validations:
      required: true
  - type: input
    id: datapack-version
    attributes:
      label: Datapack version
      description: >-
        The version of the datapack. The version can be found next
        to the datapack name in the `Installed Datapacks` advancement tab.
      placeholder: "Example: v3.1.3"
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: "Example: The Piston should extend."
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What did actually happen?
      placeholder: "Example: The Piston does not extend."
    validations:
      required: true
  - type: textarea
    id: repro-steps
    attributes:
      label: Reproduction Steps
      description: >-
        Provide information on how to reproduce this bug. You can either
        fill this section in like the example below or do something else
        just make sure your instructions are minimal and clear, as I need
        to be able to replicate your issue.
      placeholder: |
        Example:
        1. Place a Redstone Lamp in front of a Redstone Repeater
        2. Use a Lever to activate the Redstone Repeater
        3. Nothing happens
    validations:
      required: true
  - type: textarea
    id: additional
    attributes:
      label: Additional information
      description: >-
        Provide a list of any other datapacks you are using, along with their
        respective versions. If you have any screenshots, videos, or other
        information that you feel is necessary to explain the issue, feel free
        to attach them here.
