name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node.js environment
        uses: actions/setup-node@v3

      - name: Install mc-build
        run: npm i -g mc-build
      - name: Run mc-build
        run: mcb -build

      - name: Zip files
        uses: TheDoctor0/zip-release@0.6.2
        with:
          filename: "Natural-Disaster-Datapack.zip"
          type: "zip"
          path: "data pack.mcmeta pack.png LICENSE.txt README.md CHANGELOG.md"

      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          name: Natural Disaster Datapack ${{github.ref_name}}
          body_path: CHANGELOG.md
          files: Natural-Disaster-Datapack.zip
