name: Release

on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v3

      - name: Install mc-build
        run: npm i -g mc-build
      - name: Run mc-build
        run: mcb -build

      - name: Squash datapack
        uses: ComunidadAylas/PackSquash-action@v3
        with:
          artifact_name: datapack-raw
          force_include_files: icon.png
      - name: Donwload datapack-raw
        uses: actions/download-artifact@v3
        with:
          name: datapack-raw
      - name: Finish datapack
        run: |
          mv pack.zip No-Lag.zip
          zip -u No-Lag.zip LICENSE.txt README.md CHANGELOG.md

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: artifact
          path: |
            CHANGELOG.md
            No-Lag.zip

  release-github:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Donwload artifact
        uses: actions/download-artifact@v3
        with:
          name: artifact

      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          name: No Lag ${{github.ref_name}}
          body_path: CHANGELOG.md
          files: |
            No-Lag.zip
