name: Test

on:
  push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node.js environment
        uses: actions/setup-node@v3

      - name: Install mc-build
        run: npm i -g mc-build
      - name: Run mc-build
        run: mcb -build

      - name: Check minecraft commands
        uses: mcbeet/check-commands@v1
        with:
          source: /home/runner/work/test/test
          minecraft: "1.19"
